language: java
jdk: 
 - openjdk8
addons:
  sonarcloud:
    organization: "muradexpert"
    token:
      secure: "37d400320156eb1d6d6677d867f045889f80740c"
      # encrypted value of your token
services:
 - postgresql
postgres:
  adapter: postgresql
  database: shop
  username: postgres
before_script:
 - "psql -c 'create database shop;' -U postgres"
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=muradexpert_DbService
before_install:
 - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: "c5e76a84-b627-4838-a1ff-00b91bba6205"


